server:
  port: 9090
  servlet:
    context-path: /wunderlist-api

spring:
  couchbase:
    connection-string: localhost
    username: admin
    password: password


  application:
    name: wunderlist-api
  data:
    couchbase:
      bucket-name: wunderlist-app



jwt:
  secret: fasdgafdagvvfdagdfahgsdjvajgdfadghfasdhafdafdahfdahsgdfsahdfahdajfdadfsahdfadhafahvdafd
  accessTokenExpiration: 1800000
  refreshTokenExpiration: 3600000
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html